spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:meetingpoint_prod}
    username: ${DB_USERNAME:meetingpoint_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      
  flyway:
    enabled: true
    baseline-on-migrate: true
    
# 외부 API 설정 (운영용)
external-api:
  kakao:
    rest-api-key: ${KAKAO_REST_API_KEY}
    base-url: https://dapi.kakao.com
  weather:
    api-key: ${WEATHER_API_KEY}
    base-url: https://api.openweathermap.org/data/2.5
    
logging:
  level:
    com.loadmapguide_backend: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    root: INFO